- hosts: 127.0.0.1
  connection: local
  remote_user: dzigen
  vars:
    - pwd: "{{ lookup('env', 'PWD') }}"

  tasks:
    - name: up modelapi-service
      shell:
        cmd: "MONGO_INITDB_ROOT_USERNAME={{ MONGO_INITDB_ROOT_USERNAME }} \
        MONGO_INITDB_ROOT_PASSWORD={{ MONGO_INITDB_ROOT_PASSWORD }} \
        ME_CONFIG_BASICAUTH_USERNAME={{ ME_CONFIG_BASICAUTH_USERNAME }} \
        ME_CONFIG_BASICAUTH_PASSWORD={{ ME_CONFIG_BASICAUTH_PASSWORD }} \
        ME_CONFIG_MONGODB_PORT={{ ME_CONFIG_MONGODB_PORT }} \
        ME_CONFIG_MONGODB_ADMINUSERNAME={{ ME_CONFIG_MONGODB_ADMINUSERNAME }} \
        ME_CONFIG_MONGODB_ADMINPASSWORD={{ ME_CONFIG_MONGODB_ADMINPASSWORD }} \
        ME_CONFIG_MONGODB_SERVER={{ ME_CONFIG_MONGODB_SERVER }} \
        MODELAPI_VAULT_PASS={{ MODELAPI_VAULT_PASS }} \
        sh -c 'docker-compose up -d modelapi'"
        chdir: "{{ pwd }}"
      register: out
      tags:
        - up_modelapi

    - name: build modelapi-image
      shell:
        cmd: "MONGO_INITDB_ROOT_USERNAME={{ MONGO_INITDB_ROOT_USERNAME }} \
        MONGO_INITDB_ROOT_PASSWORD={{ MONGO_INITDB_ROOT_PASSWORD }} \
        ME_CONFIG_BASICAUTH_USERNAME={{ ME_CONFIG_BASICAUTH_USERNAME }} \
        ME_CONFIG_BASICAUTH_PASSWORD={{ ME_CONFIG_BASICAUTH_PASSWORD }} \
        ME_CONFIG_MONGODB_PORT={{ ME_CONFIG_MONGODB_PORT }} \
        ME_CONFIG_MONGODB_ADMINUSERNAME={{ ME_CONFIG_MONGODB_ADMINUSERNAME }} \
        ME_CONFIG_MONGODB_ADMINPASSWORD={{ ME_CONFIG_MONGODB_ADMINPASSWORD }} \
        ME_CONFIG_MONGODB_SERVER={{ ME_CONFIG_MONGODB_SERVER }} \
        MODELAPI_VAULT_PASS={{ MODELAPI_VAULT_PASS }} \
        sh -c 'docker-compose build --no-cache modelapi'"
        chdir: "{{ pwd }}"
      register: out
      tags:
        - build_modelapi

    - name: build test_modelapi-images
      shell:
        cmd: "MONGO_INITDB_ROOT_USERNAME={{ MONGO_INITDB_ROOT_USERNAME }} \
        MONGO_INITDB_ROOT_PASSWORD={{ MONGO_INITDB_ROOT_PASSWORD }} \
        ME_CONFIG_BASICAUTH_USERNAME={{ ME_CONFIG_BASICAUTH_USERNAME }} \
        ME_CONFIG_BASICAUTH_PASSWORD={{ ME_CONFIG_BASICAUTH_PASSWORD }} \
        ME_CONFIG_MONGODB_PORT={{ ME_CONFIG_MONGODB_PORT }} \
        ME_CONFIG_MONGODB_ADMINUSERNAME={{ ME_CONFIG_MONGODB_ADMINUSERNAME }} \
        ME_CONFIG_MONGODB_ADMINPASSWORD={{ ME_CONFIG_MONGODB_ADMINPASSWORD }} \
        ME_CONFIG_MONGODB_SERVER={{ ME_CONFIG_MONGODB_SERVER }} \
        MODELAPI_VAULT_PASS={{ MODELAPI_VAULT_PASS }} \
        sh -c 'docker-compose build --no-cache test_modelapi'"
        chdir: "{{ pwd }}"
      register: out
      tags:
        - build_test_modelapi

    - name: up test_modelapi-service
      shell:
        cmd: "MONGO_INITDB_ROOT_USERNAME={{ MONGO_INITDB_ROOT_USERNAME }} \
        MONGO_INITDB_ROOT_PASSWORD={{ MONGO_INITDB_ROOT_PASSWORD }} \
        ME_CONFIG_BASICAUTH_USERNAME={{ ME_CONFIG_BASICAUTH_USERNAME }} \
        ME_CONFIG_BASICAUTH_PASSWORD={{ ME_CONFIG_BASICAUTH_PASSWORD }} \
        ME_CONFIG_MONGODB_PORT={{ ME_CONFIG_MONGODB_PORT }} \
        ME_CONFIG_MONGODB_ADMINUSERNAME={{ ME_CONFIG_MONGODB_ADMINUSERNAME }} \
        ME_CONFIG_MONGODB_ADMINPASSWORD={{ ME_CONFIG_MONGODB_ADMINPASSWORD }} \
        ME_CONFIG_MONGODB_SERVER={{ ME_CONFIG_MONGODB_SERVER }} \
        MODELAPI_VAULT_PASS={{ MODELAPI_VAULT_PASS }} \
        sh -c 'docker-compose up test_modelapi'"
        chdir: "{{ pwd }}"
      register: out
      tags:
        - up_test_modelapi

    - debug:
        var: out.stdout_lines